alg_protein = 'MEILW-KTLTWILSL-IMASSEFYSDNRLSYSSQ---EEFLTYLEHYQLT-PIXXXXXXXXXXXXXXXXXXXXXX-XXXXX----X-----XX--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW'
unalg_nuc_seq = "ATGGAAATTTTGTGGAAGACGTTGACCTGGATTTTGAGCCTCATCATGGCATCATCAGAATTTTATAGTGATAACAGGCTTTCATACAGTTCTCAAGAGGAATTCCTGACATATCTTGAACACTACCAGCTAACTCCAATANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTGG"
alg_nuc_seq: str = ''
print(alg_nuc_seq)
i = 0

for aa in alg_protein:
    if aa == '-':
        alg_nuc_seq+= '---'
    else:
        codon = unalg_nuc_seq[i:i + 3]
        i =i+3
        alg_nuc_seq+= codon

print(alg_nuc_seq)
print(len(alg_nuc_seq))